name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  RANDOM_SEED: ${{ github.run_id }}

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: Test
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.5.0
        python -m pip install tox-gh-actions

    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: Cache the virtualenv
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: ${{ runner.os }}-${{ matrix.python-version }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m poetry install --with testing

    - name: Run tests
      run: |
        echo "Random seed: $RANDOM_SEED"
        export RANDOM_SEED
        chmod +x runtests.sh
        ./runtests.sh
        exit 0

  coverage:
    needs: tests
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
